### PR TITLE
Fix crash with ChatterboxGetOptionMetadata + clean up old .yy files

### PR DESCRIPTION
**Pull request by FaultyFunctions**
The `_index` argument wasn't being passed into the internal `GetOptionMetadata` method.

### CODE REVIEW

**Comment by FaultyFunctions** [comment]
This closes #45

**Comment by JujuAdams** [comment]
Thank you kindly!

**Comment by JujuAdams** [comment]
Oh wait this PR is for `master`, will have to wait a tick before I can merge this in because I need to check what might conflict on `dev` (probably nothing, but I don't have time to confirm that right now). Please make PRs for `dev` in the future since that's a bit easier my end

**Comment by FaultyFunctions** [comment]
Oh shoot my b! Gimme a few hours and I'll see if I can switch this or submit a new PR on the correct branch.

**Comment by FaultyFunctions** [comment]
Okay, I switched the branch to be merged into `dev` and it doesn't look like there are any merge conflicts. Lemme know!

**Comment by JujuAdams** [comment]
Finally got round to this. Thanks Faulty

**Pull request merged**
